### ISSUE TITLE
Convert Mercury maps to JSON objects

### ISSUE THREAD

**Issue by dram** [juliensf/mercury-json#5]
When trying to convert Mercury map to JSON object, a list of `key` and `value` pair objects is returned, instead of an object, which I think is not quite correct.

For example, with following demo code, the result is:

```
[{"key":"bar","value":["c"]},{"key":"foo","value":["a","b"]}]
```

Instead of:

```
{"bar": ["c"], "foo": ["a", "b"]}
```

Demo code:

```
:- module test.

:- interface.

:- import_module io.

:- pred main(io::di, io::uo) is det.

:- implementation.

:- import_module json.

:- import_module list.
:- import_module map.
:- import_module pair.

main(!IO) :-
    Json = json.to_json(
               map.from_assoc_list(
                   ["foo" - ["a", "b"], "bar" - ["c"]])),
    json.write_compact(Json, !IO).

```

Tested on:

```
Mercury Compiler, version rotd-2019-08-16, on x86_64-pc-linux-gnu
```

**Comment by juliensf** [comment]
Arrays of objects with members named "key" and value" is the documented way that this library represents Mercury maps in JSON.   Converting them to JSON objects where the key in the Mercury map becomes a member name in JSON might make sense when you have a Mercury map where the key is a string but not if the key has some other type.  The JSON serialisation of maps is intended to work for arbitrary key (and value) types, not just strings.

**Comment by dram** [comment]
Thanks, reasonable. I'll use `det_make_object` instead.
